import type { DayPlan } from './types'

/** Days still authored in TypeScript. A spanish plan.json file with the same day number replaces the matching entry. */
export const BUILTIN_DAYS: DayPlan[] = [
  {
    day: 4,
    title: 'Core verbs',
    isReview: false,
    vocabFocus: 'Common verbs: tener, querer, ir, hacer',
    grammarFocus: 'Tengo, quiero, voy, hago',
    listenFocus: 'Listen for these four verbs',
    practiceFocus: 'Create two sentences with each verb',
    grammar: {
      points: [
        {
          title: 'Only the forms in today’s phrases',
          rule: 'Learn these as chunks. Tener covers hunger and tener que (have to). Ir and querer are followed by a or another verb.',
          examples: [
            { spanish: 'Tengo hambre. Tengo que trabajar.', english: 'I am hungry. I have to work.' },
            { spanish: 'Quiero café. ¿Qué quieres comer?', english: 'I want coffee. What do you want to eat?' },
            { spanish: 'Voy al trabajo. ¿Adónde vas?', english: 'I am going to work. Where are you going?' },
            { spanish: 'Hago ejercicio. ¿Qué haces hoy?', english: 'I exercise. What are you doing today?' },
          ],
        },
      ],
      notYet: 'The rest of each conjugation, and the past tense.',
    },
    phrases: [
      { id: 'd4-1', spanish: 'Tengo hambre.', english: 'I am hungry.' },
      { id: 'd4-2', spanish: '¿Tienes tiempo?', english: 'Do you have time?' },
      { id: 'd4-3', spanish: 'Quiero café.', english: 'I want coffee.' },
      { id: 'd4-4', spanish: '¿Qué quieres comer?', english: 'What do you want to eat?' },
      { id: 'd4-5', spanish: 'Voy al trabajo.', english: 'I am going to work.' },
      { id: 'd4-6', spanish: '¿Adónde vas?', english: 'Where are you going?' },
      { id: 'd4-7', spanish: 'Hago ejercicio por la mañana.', english: 'I exercise in the morning.' },
      { id: 'd4-8', spanish: '¿Qué haces hoy?', english: 'What are you doing today?' },
      { id: 'd4-9', spanish: 'No tengo dinero.', english: 'I do not have money.' },
      { id: 'd4-10', spanish: 'Quiero ir a casa.', english: 'I want to go home.' },
      { id: 'd4-11', spanish: 'Vamos al parque.', english: 'We are going to the park.' },
      { id: 'd4-12', spanish: 'Hacemos la cena juntos.', english: 'We make dinner together.' },
      { id: 'd4-13', spanish: 'Tengo que trabajar.', english: 'I have to work.' },
    ],
    dialogue: {
      title: 'Evening plans',
      lines: [
        { speaker: 'Noa', spanish: '¿Qué quieres hacer esta noche?', english: 'What do you want to do tonight?' },
        { speaker: 'Diego', spanish: 'Tengo hambre. Quiero comer.', english: 'I am hungry. I want to eat.' },
        { speaker: 'Noa', spanish: 'Vamos a un restaurante.', english: 'Let’s go to a restaurant.' },
        { speaker: 'Diego', spanish: 'No tengo mucho tiempo. Tengo que trabajar mañana.', english: 'I do not have much time. I have to work tomorrow.' },
        { speaker: 'Noa', spanish: 'Entonces hacemos algo rápido.', english: 'Then let’s do something quick.' },
        { speaker: 'Diego', spanish: 'Perfecto. Voy a casa a las nueve.', english: 'Perfect. I am going home at nine.' },
      ],
    },
    practice: {
      title: 'Two sentences each',
      instruction: 'Make two sentences with tener, two with querer, two with ir, and two with hacer.',
      starters: ['Tengo… / No tengo…', 'Quiero… / ¿Qué quieres…?', 'Voy a… / Vamos a…', 'Hago… / ¿Qué haces…?'],
      tips: ['Tener is used for hunger, age, and obligation (tener que).', 'Keep the sentences short and spoken, not written first.'],
    },
  },
  {
    day: 5,
    title: 'Food & drinks',
    isReview: false,
    vocabFocus: 'Food and drinks',
    grammarFocus: 'Un, una, and quiero',
    listenFocus: 'Ordering at a restaurant',
    practiceFocus: 'Pretend to order a meal in Spanish',
    grammar: {
      points: [
        {
          title: 'Enough grammar to order',
          rule: 'Un before a masculine noun, una before a feminine one. Quiero takes a thing or a verb. You will hear desea from staff; answer with quiero.',
          examples: [
            { spanish: 'Un café. Una paella.', english: 'A coffee. A paella.' },
            { spanish: 'Quiero comer.', english: 'I want to eat.' },
            { spanish: 'Para mí, una ensalada.', english: 'For me, a salad.' },
          ],
        },
      ],
      notYet: 'Gustar, object pronouns, and the usted verb table.',
    },
    phrases: [
      { id: 'd5-1', spanish: 'Quiero comer.', english: 'I want to eat.' },
      { id: 'd5-2', spanish: 'Una mesa para dos, por favor.', english: 'A table for two, please.' },
      { id: 'd5-3', spanish: 'La carta, por favor.', english: 'The menu, please.' },
      { id: 'd5-4', spanish: 'Para mí, una paella.', english: 'For me, a paella.' },
      { id: 'd5-5', spanish: 'Quiero un café con leche.', english: 'I want a coffee with milk.' },
      { id: 'd5-6', spanish: '¿Qué recomienda?', english: 'What do you recommend?' },
      { id: 'd5-7', spanish: 'Está delicioso.', english: 'It is delicious.' },
      { id: 'd5-8', spanish: 'La cuenta, por favor.', english: 'The bill, please.' },
      { id: 'd5-9', spanish: 'Sin gluten, por favor.', english: 'Gluten-free, please.' },
      { id: 'd5-10', spanish: 'Agua con gas.', english: 'Sparkling water.' },
      { id: 'd5-11', spanish: 'Un vaso de vino tinto.', english: 'A glass of red wine.' },
      { id: 'd5-12', spanish: '¿Puedo pedir el postre?', english: 'Can I order dessert?' },
      { id: 'd5-13', spanish: 'Soy vegetariano.', english: 'I am vegetarian.' },
    ],
    dialogue: {
      title: 'At the restaurant',
      lines: [
        { speaker: 'Camarero', spanish: 'Buenas tardes. ¿Mesa para cuántos?', english: 'Good afternoon. A table for how many?' },
        { speaker: 'Alex', spanish: 'Para uno, por favor.', english: 'For one, please.' },
        { speaker: 'Camarero', spanish: '¿Qué desea beber?', english: 'What would you like to drink?' },
        { speaker: 'Alex', spanish: 'Agua y un café, por favor.', english: 'Water and a coffee, please.' },
        { speaker: 'Camarero', spanish: '¿Y para comer?', english: 'And to eat?' },
        { speaker: 'Alex', spanish: 'Quiero una tortilla y una ensalada.', english: 'I want an omelette and a salad.' },
        { speaker: 'Camarero', spanish: 'Muy bien. Enseguida.', english: 'Very good. Right away.' },
      ],
    },
    extraListen: {
      title: 'Spanish restaurant dialogue (YouTube)',
      url: 'https://www.youtube.com/results?search_query=spanish+restaurant+dialogue+beginner',
    },
    practice: {
      title: 'Order a meal',
      instruction: 'Role-play walking into a restaurant, sitting down, ordering food and drink, then asking for the bill.',
      starters: [
        'Hola, una mesa para uno, por favor.',
        '¿Qué recomienda?',
        'Para mí…',
        'La cuenta, por favor.',
      ],
      tips: ['Por favor and gracias do a lot of work.', 'If you freeze, just point at the “menu” and say esto, por favor.'],
    },
  },
  {
    day: 6,
    title: 'Family & people',
    isReview: false,
    vocabFocus: 'Family and people',
    grammarFocus: 'Mi, mis, and matching endings',
    listenFocus: 'A simple family description',
    practiceFocus: 'Describe your family or friends',
    grammar: {
      points: [
        {
          title: 'One owner word, then match the ending',
          rule: 'Mi for one person or thing, mis for more than one. The adjective follows the noun and matches it: -o/-os for masculine, -a for feminine.',
          examples: [
            { spanish: 'Mi hermana. Mis amigos.', english: 'My sister. My friends.' },
            { spanish: 'Mis amigos son simpáticos.', english: 'My friends are nice.' },
            { spanish: 'Somos una familia pequeña.', english: 'We are a small family.' },
          ],
        },
      ],
      notYet: 'Su, nuestro, and other possessive forms.',
    },
    phrases: [
      { id: 'd6-1', spanish: 'Esta es mi familia.', english: 'This is my family.' },
      { id: 'd6-2', spanish: 'Tengo un hermano y una hermana.', english: 'I have a brother and a sister.' },
      { id: 'd6-3', spanish: 'Mi madre se llama…', english: 'My mother’s name is…' },
      { id: 'd6-4', spanish: 'Mi padre es médico.', english: 'My father is a doctor.' },
      { id: 'd6-5', spanish: 'Mis amigos son muy simpáticos.', english: 'My friends are very nice.' },
      { id: 'd6-6', spanish: 'Vivo con mi pareja.', english: 'I live with my partner.' },
      { id: 'd6-7', spanish: 'No tengo hijos.', english: 'I do not have children.' },
      { id: 'd6-8', spanish: 'Mi abuela vive en la India.', english: 'My grandmother lives in India.' },
      { id: 'd6-9', spanish: 'Somos una familia pequeña.', english: 'We are a small family.' },
      { id: 'd6-10', spanish: 'Él es mi mejor amigo.', english: 'He is my best friend.' },
      { id: 'd6-11', spanish: 'Ella es muy inteligente.', english: 'She is very intelligent.' },
      { id: 'd6-12', spanish: '¿Tienes hermanos?', english: 'Do you have siblings?' },
    ],
    dialogue: {
      title: 'Talking about family',
      lines: [
        { speaker: 'Elena', spanish: '¿Tienes hermanos?', english: 'Do you have siblings?' },
        { speaker: 'Alex', spanish: 'Sí, tengo una hermana. ¿Y tú?', english: 'Yes, I have a sister. And you?' },
        { speaker: 'Elena', spanish: 'Tengo dos hermanos. Somos tres.', english: 'I have two brothers. There are three of us.' },
        { speaker: 'Alex', spanish: '¿Dónde vive tu familia?', english: 'Where does your family live?' },
        { speaker: 'Elena', spanish: 'Mis padres viven en Sevilla. Yo vivo en Londres.', english: 'My parents live in Seville. I live in London.' },
      ],
    },
    practice: {
      title: 'Describe your people',
      instruction: 'Talk about 3–4 people: names, where they live, what they do, and one quality.',
      starters: ['Esta es mi familia.', 'Tengo…', 'Mi… se llama…', 'Vive en…', 'Es muy…'],
      tips: ['Use ser for jobs and personality.', 'If you do not want to talk about family, describe friends instead.'],
    },
  },
  {
    day: 7,
    title: 'Week one review',
    isReview: true,
    vocabFocus: 'Revise Days 1–6',
    grammarFocus: 'Week-one patterns only',
    listenFocus: 'Re-listen to a dialogue from this week',
    practiceFocus: 'Speak for 5 minutes entirely in Spanish',
    grammar: {
      points: [
        {
          title: 'Nothing new',
          rule: 'Reuse the patterns you can already say. If a sentence needs a form from this list, use it. If it does not, stick to a chunk you know.',
          examples: [
            { spanish: 'Soy… / No soy…', english: 'Identity and negation.' },
            { spanish: 'Es la una. Son las…', english: 'Telling the time.' },
            { spanish: 'Tengo… Quiero… Voy… Hago…', english: 'The four core verbs.' },
            { spanish: 'Mi hermana. Mis amigos son…', english: 'Possession and agreement.' },
          ],
        },
      ],
      notYet: 'Any new tense. Today is for speaking, not a new chart.',
    },
    phrases: [
      { id: 'd7-1', spanish: 'Hola, me llamo… y soy de…', english: 'Hi, my name is… and I am from…' },
      { id: 'd7-2', spanish: 'Hoy es… y son las…', english: 'Today is… and it is…' },
      { id: 'd7-3', spanish: 'Soy ingeniero. No soy médico.', english: 'I am an engineer. I am not a doctor.' },
      { id: 'd7-4', spanish: 'Tengo hambre y quiero comer.', english: 'I am hungry and I want to eat.' },
      { id: 'd7-5', spanish: 'Voy al restaurante con mis amigos.', english: 'I am going to the restaurant with my friends.' },
      { id: 'd7-6', spanish: '¿Qué quieres beber?', english: 'What do you want to drink?' },
      { id: 'd7-7', spanish: 'Mi hermana es profesora.', english: 'My sister is a teacher.' },
      { id: 'd7-8', spanish: 'Somos de Londres.', english: 'We are from London.' },
      { id: 'd7-9', spanish: 'Hago ejercicio por la mañana.', english: 'I exercise in the morning.' },
      { id: 'd7-10', spanish: 'Hasta luego. Nos vemos el sábado.', english: 'See you later. See you on Saturday.' },
    ],
    dialogue: {
      title: 'A full beginner conversation',
      lines: [
        { speaker: 'Ana', spanish: '¡Hola! ¿Cómo estás?', english: 'Hi! How are you?' },
        { speaker: 'Alex', spanish: 'Estoy bien. Hoy es domingo. Quiero ir a un café.', english: 'I am well. Today is Sunday. I want to go to a café.' },
        { speaker: 'Ana', spanish: 'Yo también. Tengo hambre.', english: 'Me too. I am hungry.' },
        { speaker: 'Alex', spanish: 'Vamos. ¿Qué quieres comer?', english: 'Let’s go. What do you want to eat?' },
        { speaker: 'Ana', spanish: 'Una tostada y un café con leche.', english: 'Toast and a coffee with milk.' },
        { speaker: 'Alex', spanish: 'Perfecto. Mi hermana vive cerca. Es muy simpática.', english: 'Perfect. My sister lives nearby. She is very nice.' },
      ],
    },
    practice: {
      title: 'Five minutes in Spanish',
      instruction: 'Speak for five minutes without switching to English. Introduce yourself, talk about today, food, and family.',
      starters: [
        'Hola, me llamo Alex. Vivo en Londres…',
        'Hoy es… Ahora son las…',
        'Quiero… Tengo… Voy a…',
        'Mi familia… Mis amigos…',
      ],
      tips: ['Do not stop when you make a mistake. Keep speaking.', 'If you get stuck, repeat a phrase you already know.'],
      speakMinutes: 5,
    },
  },
  {
    day: 8,
    title: 'Places & directions',
    isReview: false,
    vocabFocus: 'Places and directions',
    grammarFocus: 'Está for location',
    listenFocus: 'A beginner directions dialogue',
    practiceFocus: 'Explain how to get from home to a place',
    grammar: {
      points: [
        {
          title: 'Where something is',
          rule: 'Está places a thing. Voy en plus a vehicle, or voy andando for on foot. Direction commands such as siga and gire are fixed phrases.',
          examples: [
            { spanish: 'Está a la derecha.', english: 'It is on the right.' },
            { spanish: 'Está cerca de aquí.', english: 'It is near here.' },
            { spanish: 'Voy en metro. Voy andando.', english: 'I go by metro. I go on foot.' },
          ],
        },
      ],
      notYet: 'The full estar table. Feelings come on day 11. Do not study the imperative.',
    },
    phrases: [
      { id: 'd8-1', spanish: '¿Dónde está la estación?', english: 'Where is the station?' },
      { id: 'd8-2', spanish: 'Está a la derecha.', english: 'It is on the right.' },
      { id: 'd8-3', spanish: 'Está a la izquierda.', english: 'It is on the left.' },
      { id: 'd8-4', spanish: 'Siga todo recto.', english: 'Go straight ahead.' },
      { id: 'd8-5', spanish: 'Está cerca de aquí.', english: 'It is near here.' },
      { id: 'd8-6', spanish: 'Está lejos.', english: 'It is far.' },
      { id: 'd8-7', spanish: 'Gire en la segunda calle.', english: 'Turn at the second street.' },
      { id: 'd8-8', spanish: 'El parque está al lado del café.', english: 'The park is next to the café.' },
      { id: 'd8-9', spanish: 'Voy en metro.', english: 'I go by metro.' },
      { id: 'd8-10', spanish: 'Voy andando.', english: 'I go on foot.' },
      { id: 'd8-11', spanish: '¿Cómo llego al centro?', english: 'How do I get to the centre?' },
      { id: 'd8-12', spanish: 'Vivo cerca de la estación.', english: 'I live near the station.' },
    ],
    dialogue: {
      title: 'Asking for directions',
      lines: [
        { speaker: 'Alex', spanish: 'Perdone, ¿dónde está el museo?', english: 'Excuse me, where is the museum?' },
        { speaker: 'Local', spanish: 'Siga todo recto y gire a la izquierda.', english: 'Go straight and turn left.' },
        { speaker: 'Alex', spanish: '¿Está lejos?', english: 'Is it far?' },
        { speaker: 'Local', spanish: 'No, está cerca. Diez minutos andando.', english: 'No, it is close. Ten minutes on foot.' },
        { speaker: 'Alex', spanish: 'Muchas gracias.', english: 'Thank you very much.' },
        { speaker: 'Local', spanish: 'De nada. ¡Buen día!', english: 'You’re welcome. Have a good day!' },
      ],
    },
    practice: {
      title: 'From home to a place',
      instruction: 'Explain how you get from your home to the station, a café, or work.',
      starters: ['Salgo de casa.', 'Voy andando / en metro / en autobús.', 'Sigo todo recto.', 'Está a la derecha.'],
      tips: ['Use está for location.', 'Keep it to 6–8 spoken sentences.'],
    },
  },
  {
    day: 9,
    title: 'Daily routine',
    isReview: false,
    vocabFocus: 'Daily routine vocabulary',
    grammarFocus: 'Me levanto and me gusta',
    listenFocus: 'Someone describing their day',
    practiceFocus: 'Describe your own daily routine',
    grammar: {
      points: [
        {
          title: 'Say the routine as chunks',
          rule: 'Me plus the verb is the “I” form for these routines. Me gusta takes one thing or a verb. Order the day with primero, después, and luego.',
          examples: [
            { spanish: 'Me levanto. Me ducho. Me acuesto.', english: 'I get up. I shower. I go to bed.' },
            { spanish: 'Me gusta correr.', english: 'I like to run.' },
            { spanish: 'Primero desayuno. Después trabajo.', english: 'First I have breakfast. Then I work.' },
          ],
        },
      ],
      notYet: 'Te and se, me gustan, and the full reflexive table.',
    },
    phrases: [
      { id: 'd9-1', spanish: 'Me levanto a las siete.', english: 'I get up at seven.' },
      { id: 'd9-2', spanish: 'Desayuno en casa.', english: 'I have breakfast at home.' },
      { id: 'd9-3', spanish: 'Voy al trabajo.', english: 'I go to work.' },
      { id: 'd9-4', spanish: 'Trabajo desde casa.', english: 'I work from home.' },
      { id: 'd9-5', spanish: 'Como a la una.', english: 'I have lunch at one.' },
      { id: 'd9-6', spanish: 'Por la tarde, hago ejercicio.', english: 'In the afternoon, I exercise.' },
      { id: 'd9-7', spanish: 'Ceno con mi familia.', english: 'I have dinner with my family.' },
      { id: 'd9-8', spanish: 'Me acuesto a las once.', english: 'I go to bed at eleven.' },
      { id: 'd9-9', spanish: 'Me ducho por la mañana.', english: 'I shower in the morning.' },
      { id: 'd9-10', spanish: 'Primero… después… luego…', english: 'First… after that… then…' },
      { id: 'd9-11', spanish: 'Normalmente llego a casa a las seis.', english: 'I usually get home at six.' },
      { id: 'd9-12', spanish: 'Me gusta correr.', english: 'I like to run.' },
    ],
    dialogue: {
      title: 'A normal day',
      lines: [
        { speaker: 'Lucía', spanish: '¿Cómo es tu día?', english: 'What is your day like?' },
        { speaker: 'Alex', spanish: 'Me levanto a las siete y desayuno café.', english: 'I get up at seven and have coffee for breakfast.' },
        { speaker: 'Lucía', spanish: '¿Trabajas en una oficina?', english: 'Do you work in an office?' },
        { speaker: 'Alex', spanish: 'A veces. Hoy trabajo desde casa.', english: 'Sometimes. Today I work from home.' },
        { speaker: 'Lucía', spanish: 'Por la tarde, ¿qué haces?', english: 'In the afternoon, what do you do?' },
        { speaker: 'Alex', spanish: 'Hago ejercicio. Me gusta correr.', english: 'I exercise. I like to run.' },
      ],
    },
    practice: {
      title: 'Your day, start to finish',
      instruction: 'Describe your routine from waking up to going to bed. Use first, then, later.',
      starters: ['Me levanto a las…', 'Desayuno…', 'Trabajo…', 'Por la tarde…', 'Me acuesto a las…'],
      tips: ['Reflexive verbs: me levanto, me ducho, me acuesto.', 'Do not aim for perfect grammar. Aim for a full spoken day.'],
    },
  },
  {
    day: 10,
    title: 'Regular present tense',
    isReview: false,
    vocabFocus: 'Present-tense regular verbs: -ar / -er / -ir',
    grammarFocus: 'Present endings: -ar, -er, -ir',
    listenFocus: 'Listen for conjugated verbs',
    practiceFocus: 'Conjugate 3 verbs and make sentences',
    grammar: {
      points: [
        {
          title: 'Five endings, three groups',
          rule: 'Use yo, tú, él/ella, nosotros, and ellos/ellas only. The subject pronoun is optional. Questions do not add “do”.',
          examples: [
            { spanish: 'hablo, hablas, habla, hablamos, hablan', english: '-ar: o, as, a, amos, an' },
            { spanish: 'como, comes, come, comemos, comen', english: '-er: o, es, e, emos, en' },
            { spanish: 'vivo, vives, vive, vivimos, viven', english: '-ir: o, es, e, imos, en' },
            { spanish: '¿Dónde vives?', english: 'Where do you live?' },
          ],
        },
      ],
      notYet: 'Vosotros, and stem-changing verbs. Tengo, quiero, and voy stay chunks.',
    },
    phrases: [
      { id: 'd10-1', spanish: 'Yo hablo español.', english: 'I speak Spanish.' },
      { id: 'd10-2', spanish: 'Tú hablas muy bien.', english: 'You speak very well.' },
      { id: 'd10-3', spanish: 'Ella habla inglés.', english: 'She speaks English.' },
      { id: 'd10-4', spanish: 'Como fruta por la mañana.', english: 'I eat fruit in the morning.' },
      { id: 'd10-5', spanish: '¿Comes carne?', english: 'Do you eat meat?' },
      { id: 'd10-6', spanish: 'Vivo en Londres.', english: 'I live in London.' },
      { id: 'd10-7', spanish: '¿Dónde vives?', english: 'Where do you live?' },
      { id: 'd10-8', spanish: 'Estudiamos por la noche.', english: 'We study at night.' },
      { id: 'd10-9', spanish: 'Ellos viven cerca.', english: 'They live nearby.' },
      { id: 'd10-10', spanish: 'Trabajo, trabajas, trabaja.', english: 'I work, you work, he/she works.' },
      { id: 'd10-11', spanish: 'Bebo agua.', english: 'I drink water.' },
      { id: 'd10-12', spanish: 'Escribimos mensajes.', english: 'We write messages.' },
    ],
    dialogue: {
      title: 'What we do',
      lines: [
        { speaker: 'Nico', spanish: '¿Hablas español todos los días?', english: 'Do you speak Spanish every day?' },
        { speaker: 'Alex', spanish: 'Sí. Estudio por la mañana y hablo por la noche.', english: 'Yes. I study in the morning and speak at night.' },
        { speaker: 'Nico', spanish: '¿Dónde vives ahora?', english: 'Where do you live now?' },
        { speaker: 'Alex', spanish: 'Vivo en Londres. Trabajo desde casa.', english: 'I live in London. I work from home.' },
        { speaker: 'Nico', spanish: 'Nosotros también estudiamos. Bebemos café y practicamos.', english: 'We also study. We drink coffee and practise.' },
      ],
    },
    practice: {
      title: 'Three verbs, full pattern',
      instruction: 'Pick hablar, comer, and vivir. Say yo/tú/él/nosotros/ellos, then one sentence for each verb.',
      starters: ['Yo hablo… / Tú hablas…', 'Como… / ¿Comes…?', 'Vivo en… / Vivimos en…'],
      tips: ['-ar: o, as, a, amos, an.', '-er: o, es, e, emos, en.', '-ir: o, es, e, imos, en.'],
    },
  },
  {
    day: 11,
    title: 'Estar — place and feeling',
    isReview: false,
    vocabFocus: 'Estar: estoy, estás, está…',
    grammarFocus: 'Ser or estar',
    listenFocus: 'Listen for ser vs estar',
    practiceFocus: 'Describe where you are and how you feel',
    grammar: {
      points: [
        {
          title: 'Who you are, or where and how you are now',
          rule: 'Ser is identity and origin. Estar is location and a feeling right now. Say estoy, estás, está, estamos, están. Cansado or cansada matches you.',
          examples: [
            { spanish: 'Soy ingeniero.', english: 'I am an engineer.' },
            { spanish: 'Estoy en casa.', english: 'I am at home.' },
            { spanish: 'Estoy cansado.', english: 'I am tired.' },
            { spanish: 'Estoy cansada.', english: 'I am tired. (feminine)' },
          ],
        },
      ],
      notYet: 'The rarer ser/estar contrasts. La sopa está caliente can stay a chunk.',
    },
    phrases: [
      { id: 'd11-1', spanish: 'Estoy en casa.', english: 'I am at home.' },
      { id: 'd11-2', spanish: '¿Dónde estás?', english: 'Where are you?' },
      { id: 'd11-3', spanish: 'Estoy cansado.', english: 'I am tired.' },
      { id: 'd11-4', spanish: 'Estoy bien.', english: 'I am well / I am fine.' },
      { id: 'd11-5', spanish: 'Está feliz hoy.', english: 'He/she is happy today.' },
      { id: 'd11-6', spanish: 'El café está aquí.', english: 'The café is here.' },
      { id: 'd11-7', spanish: 'Estamos en Londres.', english: 'We are in London.' },
      { id: 'd11-8', spanish: 'No estoy ocupado.', english: 'I am not busy.' },
      { id: 'd11-9', spanish: 'Soy ingeniero, pero ahora estoy de vacaciones.', english: 'I am an engineer, but now I am on holiday.' },
      { id: 'd11-10', spanish: 'La sopa está caliente.', english: 'The soup is hot (right now).' },
      { id: 'd11-11', spanish: '¿Cómo estás hoy?', english: 'How are you today?' },
      { id: 'd11-12', spanish: 'Estoy un poco nervioso.', english: 'I am a bit nervous.' },
    ],
    dialogue: {
      title: 'Where and how',
      lines: [
        { speaker: 'Inés', spanish: '¿Dónde estás?', english: 'Where are you?' },
        { speaker: 'Alex', spanish: 'Estoy en casa. Estoy un poco cansado.', english: 'I am at home. I am a bit tired.' },
        { speaker: 'Inés', spanish: '¿Estás ocupado?', english: 'Are you busy?' },
        { speaker: 'Alex', spanish: 'No. ¿Y tú? ¿Cómo estás?', english: 'No. And you? How are you?' },
        { speaker: 'Inés', spanish: 'Estoy bien. Estoy en el parque con mis amigos.', english: 'I am well. I am in the park with my friends.' },
        { speaker: 'Alex', spanish: 'Eres muy sociable. Yo estoy tranquilo hoy.', english: 'You are very sociable. I am calm today.' },
      ],
    },
    practice: {
      title: 'Place + feeling',
      instruction: 'Say where you are, how you feel, and contrast one ser fact with one estar moment.',
      starters: ['Estoy en…', 'Hoy estoy…', 'Soy…, pero ahora estoy…', 'Mis amigos están…'],
      tips: ['Ser = who/what you are. Estar = where you are and how you feel.', 'Cansado/a agrees with gender.'],
    },
  },
  {
    day: 12,
    title: 'Shopping',
    isReview: false,
    vocabFocus: 'Shopping: prices, clothes, sizes',
    grammarFocus: 'Cuesta, esto, me lo llevo',
    listenFocus: 'A Spanish shopping dialogue',
    practiceFocus: 'Role-play buying something',
    grammar: {
      points: [
        {
          title: 'Shop sentences, not pronoun rules',
          rule: 'Ask the price with cuesta. Point with esto. Me lo llevo is one fixed sentence. Hay means “there is”. Staff may say tiene; you answer with busco, puedo, and pago.',
          examples: [
            { spanish: '¿Cuánto cuesta?', english: 'How much does it cost?' },
            { spanish: '¿Puedo probarme esto?', english: 'Can I try this on?' },
            { spanish: 'Me lo llevo.', english: 'I’ll take it.' },
            { spanish: '¿Hay descuento?', english: 'Is there a discount?' },
          ],
        },
      ],
      notYet: 'Object pronouns and este / esta / estos. Leave me lo llevo whole.',
    },
    phrases: [
      { id: 'd12-1', spanish: '¿Cuánto cuesta?', english: 'How much does it cost?' },
      { id: 'd12-2', spanish: 'Cuesta veinte euros.', english: 'It costs twenty euros.' },
      { id: 'd12-3', spanish: '¿Tiene una talla más grande?', english: 'Do you have a bigger size?' },
      { id: 'd12-4', spanish: '¿Puedo probarme esto?', english: 'Can I try this on?' },
      { id: 'd12-5', spanish: 'Me lo llevo.', english: 'I’ll take it.' },
      { id: 'd12-6', spanish: 'Es demasiado caro.', english: 'It is too expensive.' },
      { id: 'd12-7', spanish: '¿Hay descuento?', english: 'Is there a discount?' },
      { id: 'd12-8', spanish: 'Pago con tarjeta.', english: 'I am paying by card.' },
      { id: 'd12-9', spanish: 'Busco una camisa azul.', english: 'I am looking for a blue shirt.' },
      { id: 'd12-10', spanish: '¿De qué color lo quiere?', english: 'What colour would you like?' },
      { id: 'd12-11', spanish: 'Solo estoy mirando.', english: 'I am just looking.' },
      { id: 'd12-12', spanish: '¿Dónde está el probador?', english: 'Where is the fitting room?' },
    ],
    dialogue: {
      title: 'In the shop',
      lines: [
        { speaker: 'Dependienta', spanish: 'Hola, ¿le ayudo?', english: 'Hi, can I help you?' },
        { speaker: 'Alex', spanish: 'Sí. Busco una chaqueta. ¿Cuánto cuesta esta?', english: 'Yes. I am looking for a jacket. How much is this one?' },
        { speaker: 'Dependienta', spanish: 'Cuesta cuarenta euros. ¿Qué talla usa?', english: 'It costs forty euros. What size do you wear?' },
        { speaker: 'Alex', spanish: 'Mediana. ¿Puedo probarme esto?', english: 'Medium. Can I try this on?' },
        { speaker: 'Dependienta', spanish: 'Claro. El probador está a la derecha.', english: 'Of course. The fitting room is on the right.' },
        { speaker: 'Alex', spanish: 'Me queda bien. Me lo llevo. Pago con tarjeta.', english: 'It fits well. I’ll take it. I’ll pay by card.' },
      ],
    },
    practice: {
      title: 'Buy something',
      instruction: 'Role-play buying a shirt or coffee: ask the price, size or options, then pay.',
      starters: ['Hola, busco…', '¿Cuánto cuesta?', '¿Puedo probarme esto?', 'Me lo llevo. Pago con tarjeta.'],
      tips: ['You can survive a shop with five phrases.', 'If the number is fast, ask: ¿Puede repetir, por favor?'],
    },
  },
  {
    day: 13,
    title: 'Yesterday',
    isReview: false,
    vocabFocus: 'Past basics: fui, hice, comí, vi, tuve',
    grammarFocus: 'Yesterday as chunks',
    listenFocus: 'A simple story about yesterday',
    practiceFocus: 'Tell the story of what you did yesterday',
    grammar: {
      points: [
        {
          title: 'Memorise the words, not the tense',
          rule: 'Ayer sets the story in the past. No still goes before the verb. Fue means “it was”. Trabajé is the one regular pattern worth copying: an -ar verb’s “I” form ends in -é.',
          examples: [
            { spanish: 'Ayer fui al trabajo.', english: 'Yesterday I went to work.' },
            { spanish: 'Hice ejercicio. Comí. Vi. Tuve.', english: 'I did. I ate. I saw. I had.' },
            { spanish: 'No fui a casa temprano.', english: 'I did not go home early.' },
            { spanish: 'Fue un día largo. Estuve en casa.', english: 'It was a long day. I was at home.' },
          ],
        },
      ],
      notYet: 'The preterite chart, the imperfect, and every other past form.',
    },
    phrases: [
      { id: 'd13-1', spanish: 'Ayer fui al trabajo.', english: 'Yesterday I went to work.' },
      { id: 'd13-2', spanish: 'Hice ejercicio.', english: 'I did exercise / I worked out.' },
      { id: 'd13-3', spanish: 'Comí en un restaurante.', english: 'I ate at a restaurant.' },
      { id: 'd13-4', spanish: 'Vi una película.', english: 'I watched a film.' },
      { id: 'd13-5', spanish: 'Tuve una reunión.', english: 'I had a meeting.' },
      { id: 'd13-6', spanish: 'No fui a casa temprano.', english: 'I did not go home early.' },
      { id: 'd13-7', spanish: '¿Qué hiciste ayer?', english: 'What did you do yesterday?' },
      { id: 'd13-8', spanish: 'Por la mañana trabajé.', english: 'In the morning I worked.' },
      { id: 'd13-9', spanish: 'Por la noche cené con amigos.', english: 'At night I had dinner with friends.' },
      { id: 'd13-10', spanish: 'Fue un día largo.', english: 'It was a long day.' },
      { id: 'd13-11', spanish: 'Estuve en casa.', english: 'I was at home.' },
      { id: 'd13-12', spanish: 'Me gustó mucho.', english: 'I liked it a lot.' },
    ],
    dialogue: {
      title: 'What happened yesterday',
      lines: [
        { speaker: 'Omar', spanish: '¿Qué hiciste ayer?', english: 'What did you do yesterday?' },
        { speaker: 'Alex', spanish: 'Por la mañana fui al trabajo. Tuve muchas reuniones.', english: 'In the morning I went to work. I had many meetings.' },
        { speaker: 'Omar', spanish: '¿Y por la tarde?', english: 'And in the afternoon?' },
        { speaker: 'Alex', spanish: 'Hice ejercicio y después comí en casa.', english: 'I worked out and then I ate at home.' },
        { speaker: 'Omar', spanish: 'Por la noche vi una película. Fue muy buena.', english: 'At night I watched a film. It was very good.' },
        { speaker: 'Alex', spanish: 'Qué bien. Yo estuve cansado. Fue un día largo.', english: 'Nice. I was tired. It was a long day.' },
      ],
    },
    practice: {
      title: 'Yesterday in three parts',
      instruction: 'Tell morning, afternoon, and night. Use fui, hice, comí, vi, or tuve at least once each if you can.',
      starters: ['Ayer por la mañana…', 'Por la tarde hice…', 'Por la noche vi / cené…', 'Fue un día…'],
      tips: ['These are useful irregular past forms — learn them as chunks.', 'Keep the story moving. Do not conjugate tables out loud.'],
    },
  },
  {
    day: 14,
    title: 'Full review',
    isReview: true,
    vocabFocus: 'Your weakest 30–50 words',
    grammarFocus: 'Only what the story uses',
    listenFocus: 'Re-watch your favourite beginner content',
    practiceFocus: 'A 5–10 minute self-introduction and daily-life story',
    grammar: {
      points: [
        {
          title: 'Three time frames',
          rule: 'Your story needs present, right now, and yesterday. If a sentence does not fit one of these, describe around the missing word and keep talking.',
          examples: [
            { spanish: 'Soy… Vivo… Trabajo… Me levanto…', english: 'Who you are and your routine.' },
            { spanish: 'Ahora estoy…', english: 'Where you are and how you feel.' },
            { spanish: 'Ayer fui… Hice… Comí…', english: 'What you did yesterday.' },
          ],
        },
      ],
      notYet: 'Any pattern you cannot use in the 5–10 minute story.',
    },
    phrases: [
      { id: 'd14-1', spanish: 'Hola, me llamo Alex. Vivo en Londres.', english: 'Hi, my name is Alex. I live in London.' },
      { id: 'd14-2', spanish: 'Trabajo como ingeniero de software.', english: 'I work as a software engineer.' },
      { id: 'd14-3', spanish: 'Hoy trabajo desde casa.', english: 'Today I work from home.' },
      { id: 'd14-4', spanish: 'Me gusta correr y estudiar español.', english: 'I like to run and study Spanish.' },
      { id: 'd14-5', spanish: 'Por la mañana me levanto y desayuno.', english: 'In the morning I get up and have breakfast.' },
      { id: 'd14-6', spanish: 'Ayer fui al trabajo y tuve reuniones.', english: 'Yesterday I went to work and had meetings.' },
      { id: 'd14-7', spanish: 'Quiero un café y algo de comer.', english: 'I want a coffee and something to eat.' },
      { id: 'd14-8', spanish: 'Mi familia es pequeña. Tengo una hermana.', english: 'My family is small. I have a sister.' },
      { id: 'd14-9', spanish: 'Vivo cerca de la estación. Voy en metro.', english: 'I live near the station. I go by metro.' },
      { id: 'd14-10', spanish: 'Ahora estoy en casa y estoy bien.', english: 'Right now I am at home and I am well.' },
      { id: 'd14-11', spanish: '¿Puede repetir, por favor?', english: 'Can you repeat, please?' },
      { id: 'd14-12', spanish: 'No entiendo. Más despacio, por favor.', english: 'I do not understand. More slowly, please.' },
    ],
    dialogue: {
      title: 'A longer beginner story',
      lines: [
        { speaker: 'Alex', spanish: 'Hola. Me llamo Alex. Soy de Londres y trabajo como ingeniero.', english: 'Hi. My name is Alex. I am from London and I work as an engineer.' },
        { speaker: 'Alex', spanish: 'Hoy es jueves. Me levanto a las siete y trabajo desde casa.', english: 'Today is Thursday. I get up at seven and work from home.' },
        { speaker: 'Alex', spanish: 'A mediodía como algo simple. Por la tarde hago ejercicio.', english: 'At midday I eat something simple. In the afternoon I exercise.' },
        { speaker: 'Alex', spanish: 'Ayer fui a un restaurante con un amigo. Pedí una ensalada y un café.', english: 'Yesterday I went to a restaurant with a friend. I ordered a salad and a coffee.' },
        { speaker: 'Alex', spanish: 'Estoy un poco cansado, pero estoy bien. Me gusta estudiar español todos los días.', english: 'I am a bit tired, but I am well. I like studying Spanish every day.' },
      ],
    },
    extraListen: {
      title: 'Search beginner Spanish stories (YouTube)',
      url: 'https://www.youtube.com/results?search_query=beginner+spanish+slow+conversation',
    },
    practice: {
      title: 'Your two-week story',
      instruction: 'Give a 5–10 minute self-introduction and daily-life story. Cover who you are, today, family, food, and yesterday.',
      starters: [
        'Hola, me llamo… Vivo en… Trabajo como…',
        'Hoy es… Me levanto… Trabajo…',
        'Mi familia… Mis amigos…',
        'Ayer fui… Hice… Comí… Vi…',
      ],
      tips: [
        'This is the point of the two weeks: using Spanish, not finishing grammar.',
        'If a word is missing, describe around it and keep talking.',
      ],
      speakMinutes: 8,
    },
  },
]
